apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "certificate-form.fullname" . }}
  labels:
    {{- include "certificate-form.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.deployment.replicaCount }}
  selector:
    matchLabels: {{- include "certificate-form.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "certificate-form.selectorLabels" . | nindent 8 }}
    spec:
      # serviceAccountName created by the Cloud Platform environment
      serviceAccountName: cd-serviceaccount
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.deployment.image.repository }}:{{ .Values.app.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADMIN_GITHUB_TOKEN
              value:
                {{ .Values.app.deployment.env.ADMIN_GITHUB_TOKEN | quote }}
            - name: ADMIN_GANDI_TOKEN
              value:
                {{ .Values.app.deployment.env.ADMIN_GANDI_TOKEN | quote }}
            - name: ADMIN_SLACK_TOKEN
              value:
                {{ .Values.app.deployment.env.ADMIN_SLACK_TOKEN | quote }}
            - name: AUTH0_DOMAIN
              value: {{ .Values.app.deployment.env.AUTH0_DOMAIN | quote }}
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.app.deployment.env.AUTH0_CLIENT_ID | quote }}
            - name: AUTH0_CLIENT_SECRET
              value:
                {{ .Values.app.deployment.env.AUTH0_CLIENT_SECRET | quote }}
            - name: APP_SECRET_KEY
              value: {{ .Values.app.deployment.env.APP_SECRET_KEY | quote }}
            - name: FLASK_DEBUG
              value: {{ .Values.app.deployment.env.FLASK_DEBUG | quote }}
            - name: SENTRY_DSN_KEY
              value: {{ .Values.app.deployment.env.SENTRY_DSN_KEY }}
            - name: SENTRY_ENV
              value: {{ .Values.app.deployment.env.SENTRY_ENV }}

          ports:
            - name: http
              containerPort: 80
