apiVersion: v1
kind: Service
metadata:
  name: { { include "application.fullname" . } }
  labels: { { - include "application.labels" . | nindent 4 } }
spec:
  ports:
    - port: 80
      targetPort: 4567
      name: https
  selector: { { - include "application.selectorLabels" . | nindent 4 } }
